export const icons = {
  arrowLeft: require('../assets/icons/arrow_left_48.png'),
  artist: require('../assets/icons/artist_48.png'),
  bookmark: require('../assets/icons/bookmark_48.png'),
  brightness: require('../assets/icons/brightness_48.png'),
  calender: require('../assets/icons/calender_48.png'),
  category: require('../assets/icons/category_48.png'),
  copy: require('../assets/icons/copy_48.png'),
  filter: require('../assets/icons/filter_48.png'),
  heart: require('../assets/icons/heart_48.png'),
  home: require('../assets/icons/home_48.png'),
  korean: require('../assets/icons/korean_48.png'),
  location: require('../assets/icons/location_48.png'),
  magnify: require('../assets/icons/magnify_48.png'),
  menu: require('../assets/icons/menu_48.png'),
  more: require('../assets/icons/more_48.png'),
  price: require('../assets/icons/price_48.png'),
  right: require('../assets/icons/right_48.png'),
  search: require('../assets/icons/search_48.png'),
  setting: require('../assets/icons/setting_48.png'),
  share: require('../assets/icons/share_48.png'),
  user: require('../assets/icons/user_48.png'),
  logo: require('../assets/icons/logo_100.png'),
};
